name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  us:
    runs-on: ubuntu-latest
    environment: GoogleDDNSClient
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/googleddnsclient .
            --build-arg GOOGLE_USERNAME_V6="${{ secrets.GOOGLE_USERNAME_V6 }}"
            --build-arg GOOGLE_PASSWORD_V6="${{ secrets.GOOGLE_PASSWORD_V6 }}"
            --build-arg DOMAIN_NAME_V6="${{ secrets.DOMAIN_NAME_V6 }}"
            --build-arg GOOGLE_USERNAME_V4="${{ secrets.GOOGLE_USERNAME_V4 }}"
            --build-arg GOOGLE_PASSWORD_V4="${{ secrets.GOOGLE_PASSWORD_V4 }}"
            --build-arg DOMAIN_NAME_V4="${{ secrets.DOMAIN_NAME_V4 }}"


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/googleddnsclient

  timo:
    runs-on: ubuntu-latest
    environment: TIMO
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/googleddnsclient .
              --build-arg GOOGLE_USERNAME_V6="${{ secrets.GOOGLE_USERNAME_V6 }}"
              --build-arg GOOGLE_PASSWORD_V6="${{ secrets.GOOGLE_PASSWORD_V6 }}"
              --build-arg DOMAIN_NAME_V6="${{ secrets.DOMAIN_NAME_V6 }}"
              --build-arg GOOGLE_USERNAME_V4="${{ secrets.GOOGLE_USERNAME_V4 }}"
              --build-arg GOOGLE_PASSWORD_V4="${{ secrets.GOOGLE_PASSWORD_V4 }}"
              --build-arg DOMAIN_NAME_V4="${{ secrets.DOMAIN_NAME_V4 }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/googleddnsclient